[tool.poetry]
name = "morgan"
version = "0.11.2"
description = "PyPI Mirror for Offline Environments"
authors = ["Ido Perlmuter <ido@ido50.net>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.7"
packaging = "^21.3"
importlib-metadata = {version = "^4.12.0", optional = true, python = "<3.8"}
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[tool.poetry.scripts]
morgan = "morgan:main"

[tool.black]
line-length = 80
target-version = ['py37']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
